docker:
  image: yegor256/rultor
assets:
  settings.xml: "portlek/secret-repo#configs/settings.xml"
  pubring.gpg: "portlek/secret-repo#configs/pubring.gpg"
  secring.gpg: "portlek/secret-repo#configs/secring.gpg"
  "gradle.properties": "portlek/secret-repo#configs/gradle.properties" 
architect:
  - portlek
merge:
  script: |
    chmod +x gradlew
    ./gradlew -Dfile.encoding=utf-8 shadowjar
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    chmod +x gradlew
    ./gradlew -Dgradle.user.home="/home/r" -Dfile.encoding=utf-8 -PconfigsVersion="${tag}" uploadArchives closeAndReleaseRepository
