docker:
  image: yegor256/rultor
assets:
  settings.xml: "portlek/secret-repo#configs/settings.xml"
  pubring.gpg: "portlek/secret-repo#configs/pubring.gpg"
  secring.gpg: "portlek/secret-repo#configs/secring.gpg"
architect:
  - portlek
merge:
  script: |
    ./gradlew shadowjar
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    ./gradlew -PconfigsVersion="${tag}" uploadArchives
